### ISSUE TITLE
Consider bounding by `AsyncRead + AsyncWrite`.

### ISSUE THREAD

**Issue by carllerche** [hyperium/http-connection#3]
Currently, the `HttpConnection` trait has no bounds. Consider adding an `AsyncRead + AsyncWrite` bound.

I know that @LucioFranco explicitly left off these bounds, so perhaps he can elaborate on this.

Secondly, we can enumerate the locations where we expect to use `HttpConnection` and see how omitting the bounds works in practice.

**Comment by carllerche** [comment]
cc @seanmonstar

**Comment by LucioFranco** [comment]
@carllerche I decided to remove the bounds mainly because the main http crate doesn't have any async related items and I wanted to continue that philosophy. In my findings the extra bounds are only needed on the trait alias `MakeHttpConnection` and no where else really. Which means the impact is very minor.

**Comment by carllerche** [comment]
@LucioFranco do you have usage examples?

**Comment by LucioFranco** [comment]
@carllerche this is the only location so far I've had to add the extra bounds. https://github.com/tower-rs/tower-http/blob/master/tower-http-util/src/connection.rs#L17

**Comment by LucioFranco** [comment]
Here is where the trait alias is used https://github.com/tower-rs/tower-hyper/blob/master/src/client/connect.rs#L88

and here is where the `HttpConnection` trait is used to extract connection info.

https://github.com/tower-rs/tower-hyper/blob/master/src/client/connect.rs#L200

**Comment by seanmonstar** [comment]
(I'm not ignoring, I just truly don't know how I feel. Both arguments make sense, and I'm not sure how important it is anyways...)

**Comment by carllerche** [comment]
I will defer to @LucioFranco's initial design for the first release. I also see how having a standalone trait could be applied to `T: Service` as well.
